/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/claims/{tenant_id}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Any non-empty UTF-8 string, percent-encoded in the path. The server
                 *     enforces a 256-byte limit on the decoded value (JSON Schema
                 *     `maxLength` counts characters, not bytes).
                 */
                tenant_id: components["parameters"]["TenantId"];
                /** @description Caller-supplied RFC 9562 UUIDv7, lowercase and hyphenated. */
                id: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        /**
         * Redeem a claim
         * @description Returns the stored bytes. The server does not verify integrity. The
         *     redeemer MUST check `size` and `sha256` against its ticket.
         */
        get: operations["redeemClaim"];
        /**
         * Check in a claim
         * @description Stores the raw request body under a key derived from `tenant_id` and
         *     `id`. Idempotent: repeating the same request overwrites the same
         *     object. The ticket is returned only after a durable write.
         */
        put: operations["checkInClaim"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document */
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 0199a1c2-7b3e-7d4a-9c1f-2e5b8a6d4f10 */
        UUIDv7: string;
        Sha256: string;
        /**
         * @description Canonical, versioned claim ticket. Shared by the HTTP API, the
         *     RabbitMQ `claim` field, and every redeemer. Carries no storage key.
         * @example {
         *       "v": 1,
         *       "tenant_id": "acme",
         *       "id": "0199a1c2-7b3e-7d4a-9c1f-2e5b8a6d4f10",
         *       "size": 3145728,
         *       "sha256": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
         *       "content_type": "application/json"
         *     }
         */
        Ticket: {
            /**
             * @description Format indicator. Redeemers reject any other value.
             * @constant
             */
            v: 1;
            tenant_id: string;
            id: components["schemas"]["UUIDv7"];
            size: number;
            sha256: components["schemas"]["Sha256"];
            /** @description Advisory only. Never stored as object metadata. */
            content_type?: string | null;
        };
        TicketEnvelope: {
            ticket: components["schemas"]["Ticket"];
        };
        Error: {
            /** @enum {string} */
            error: "invalid_tenant" | "invalid_id" | "not_found" | "too_large" | "integrity_mismatch" | "store_unavailable";
        };
        Health: {
            /** @constant */
            status: "ok";
        };
    };
    responses: {
        /** @description `invalid_tenant` or `invalid_id`. Permanent. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `not_found`. Permanent. Dead-letter, do not requeue. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `too_large`. Body exceeds `claim_check.max_bytes`. Permanent. */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `integrity_mismatch`. Body does not match `x-ankusa-sha256`. Permanent. */
        IntegrityMismatch: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `store_unavailable`. Transient. Retry. */
        StoreUnavailable: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Any non-empty UTF-8 string, percent-encoded in the path. The server
         *     enforces a 256-byte limit on the decoded value (JSON Schema
         *     `maxLength` counts characters, not bytes).
         */
        TenantId: string;
        /** @description Caller-supplied RFC 9562 UUIDv7, lowercase and hyphenated. */
        ClaimId: components["schemas"]["UUIDv7"];
    };
    requestBodies: never;
    headers: {
        /** @description Seconds to wait before retrying. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    redeemClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Any non-empty UTF-8 string, percent-encoded in the path. The server
                 *     enforces a 256-byte limit on the decoded value (JSON Schema
                 *     `maxLength` counts characters, not bytes).
                 */
                tenant_id: components["parameters"]["TenantId"];
                /** @description Caller-supplied RFC 9562 UUIDv7, lowercase and hyphenated. */
                id: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The claim's bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    checkInClaim: {
        parameters: {
            query?: never;
            header?: {
                /** @description Expected lowercase hex SHA-256 of the body. A mismatch returns 422. */
                "x-ankusa-sha256"?: components["schemas"]["Sha256"];
            };
            path: {
                /**
                 * @description Any non-empty UTF-8 string, percent-encoded in the path. The server
                 *     enforces a 256-byte limit on the decoded value (JSON Schema
                 *     `maxLength` counts characters, not bytes).
                 */
                tenant_id: components["parameters"]["TenantId"];
                /** @description Caller-supplied RFC 9562 UUIDv7, lowercase and hyphenated. */
                id: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        /**
         * @description Raw bytes, at most `claim_check.max_bytes`. The request
         *     `content-type`, if any, is recorded in the ticket as advisory
         *     metadata only.
         */
        requestBody: {
            content: {
                "*/*": unknown;
            };
        };
        responses: {
            /** @description Claim stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["TooLarge"];
            422: components["responses"]["IntegrityMismatch"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document served by this node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": unknown;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listener is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
