/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/claims/{tenant_id}/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The claim's tenant. Never needs encoding. */
                tenant_id: components["parameters"]["TenantId"];
                /** @description The claim's id, a canonical (uppercase) ULID. */
                claim_id: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        /**
         * Read a claim's bytes
         * @description Returns exactly the claim's bytes. Claims are written once and never
         *     rewritten, so a response is cacheable forever. The server does not
         *     verify integrity: the reader MUST check the bytes against the
         *     message's `sha256` (a ranged read can only be checked once the whole
         *     claim has been reassembled).
         *
         *     One `bytes` range is served as `206`; several ranges, another unit, a
         *     malformed `Range`, or any `If-Range` (claims carry no validator) are
         *     ignored and answered `200` with the whole claim.
         */
        get: operations["readClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example acme */
        TenantId: string;
        /**
         * @description A ULID in canonical form: 26 characters of uppercase Crockford
         *     base32. The first 48 bits are the pack's creation time in Unix
         *     milliseconds; the last 16 are the claim's position in its pack.
         * @example 01M39VMD8RA3C5HR4RBV67Y002
         */
        ClaimId: string;
        /**
         * @description A claim-check ref, as carried in a queue message's `claim` field.
         *     Segments: tenant and claim id. The digest to check the bytes against
         *     is the message's `sha256` field (lowercase hex), not part of the ref.
         * @example urn:ankusa:claim:v1:acme:01M39VMD8RA3C5HR4RBV67Y002
         */
        Ref: string;
        Error: {
            /** @enum {string} */
            error: "invalid_tenant" | "invalid_id" | "not_found" | "store_unavailable";
        };
        Health: {
            /** @constant */
            status: "ok";
        };
    };
    responses: {
        /** @description `invalid_tenant` or `invalid_id` (not a canonical ULID). Permanent. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `not_found`: no such claim (expired by retention, never written, or no such route). Permanent. Dead-letter, do not requeue. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `store_unavailable`. Transient. Retry. */
        StoreUnavailable: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The claim's tenant. Never needs encoding. */
        TenantId: components["schemas"]["TenantId"];
        /** @description The claim's id, a canonical (uppercase) ULID. */
        ClaimId: components["schemas"]["ClaimId"];
    };
    requestBodies: never;
    headers: {
        /**
         * @description Always `private, max-age=31536000, immutable`: the path is a
         *     capability, so only the reader may cache it.
         */
        CacheControl: string;
        /** @description Always `bytes`. */
        AcceptRanges: "bytes";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readClaim: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One byte range: `bytes=first-last`, `bytes=first-` or
                 *     `bytes=-suffix_length` (RFC 9110 §14.1.2). `last` past the claim's
                 *     end is clamped to it.
                 */
                Range?: string;
            };
            path: {
                /** @description The claim's tenant. Never needs encoding. */
                tenant_id: components["parameters"]["TenantId"];
                /** @description The claim's id, a canonical (uppercase) ULID. */
                claim_id: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The claim's bytes. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description The requested range of the claim's bytes. */
            206: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    /** @description `bytes first-last/length`, `length` the whole claim's size. */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /**
             * @description The range starts at or past the claim's end (or is `bytes=-0`, or
             *     the claim is empty). Empty body.
             */
            416: {
                headers: {
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    /** @description `bytes *\/length`, `length` the whole claim's size. */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listener is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
