/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Both listeners answer this path, with a different body: the operator API
         *     reports the instance and the roles this node runs, the route-management
         *     API reports the size of the route table it is enforcing.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description The node's `Ankusa.Metrics` scrape: ingest, verification, WAL commit,
         *     load shedding, quarantine, dispatch, compaction, and claim-check
         *     series. Only the events this node emits appear — an edge node has no
         *     dispatch series, a storage node has no ingest series.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The effective, redacted configuration
         * @description The whole `Ankusa.Config` as the node resolved it: defaults, then the
         *     YAML file, then env overrides. Secrets are redacted by key name
         *     (`secret`, `password`, `secret_access_key`, `token`, `sasl`, `nkey_seed`)
         *     and by shape (a URI password becomes `user:[REDACTED]`), so this
         *     is safe to hand to anyone who can reach the port.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dead-lettered hooks
         * @description Newest first, metadata only — bodies are never returned. Results are
         *     this node's DLQ file; with several dispatch nodes, ask each one.
         */
        get: operations["listDeadLetters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dlq/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-deliver dead-lettered hooks
         * @description Re-delivers matching entries through their source's configured sinks.
         *     Replay is at-least-once: an entry already delivered upstream but not
         *     recorded as such will be delivered again, so consumers should dedupe on
         *     the envelope id. Entries stay in the DLQ — replay does not remove them.
         */
        post: operations["replayDeadLetters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent quarantined hooks
         * @description The edge node's in-memory recent list (at most 200 entries), newest
         *     first. Metadata only — bodies are never returned. The durable record
         *     lives in `quarantine/quarantine.log` on the node's data volume.
         */
        get: operations["listQuarantined"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry run — what would happen to this request?
         * @description Runs the same decision the guard runs, and reports it: the global IP
         *     rules first, then route matching, then the matched route's own rules.
         *     Nothing is captured, no counter moves, and the decision cache is
         *     neither read nor written — a dry run cannot make a path look hot, and
         *     it never answers from an entry another request wrote. This is the
         *     endpoint that turns "why was my webhook rejected" into one call, and it
         *     is worth using before changing any route.
         *
         *     `ip_rule` is the rule that *decided* an IP question, with the list it
         *     came from (`scope`); it is `null` whenever no rule decided — a list's
         *     `default` (nothing matched), or a reason that is not an IP decision at
         *     all.
         */
        post: operations["testRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List route definitions
         * @description Ordered by id, which is a total order over the slug alphabet and so also
         *     a pagination cursor. `next_cursor` is `null` on the last page.
         */
        get: operations["listRoutes"];
        put?: never;
        /**
         * Create a route definition
         * @description `id` is optional: without one, a lowercase ULID is generated. A taken id
         *     is a `409 duplicate_route`, and an **enabled** route may not capture the
         *     same normalized path and any of the same methods as another enabled
         *     route (two disabled routes are free to collide — they capture nothing).
         *     Past `routes.max_routes` the answer is `409 too_many_routes`; nothing is
         *     ever evicted, because an evicted route would start rejecting real
         *     webhooks.
         *
         *     The id `test` is **not** reserved: only the `POST /admin/routes/test`
         *     *dry run* shadows this path, and it shadows it for `POST` alone. `POST
         *     /admin/routes` with `{"id": "test"}` creates that route like any other
         *     id, and `GET`/`PUT`/`PATCH`/`DELETE /admin/routes/test` then address it
         *     normally.
         */
        post: operations["createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        /** Fetch one route definition */
        get: operations["getRoute"];
        /**
         * Replace a route definition
         * @description A full definition, `PUT`-idempotent: the `id` comes from the path (a body
         *     `id` is ignored), `inserted_at` is preserved, and `updated_at` moves. A
         *     `PUT` for an id that does not exist yet *creates* it, so the cap applies
         *     to that case too.
         */
        put: operations["replaceRoute"];
        post?: never;
        /**
         * Delete a route definition
         * @description Immediate: the guard stops capturing the route on the next request, with
         *     no cache TTL to wait out — the decision cache is keyed by the published
         *     snapshot's epoch, so a mutation makes every cached decision unreachable.
         *     Whether a restart brings the route back is the store's question: the
         *     default ETS store re-seeds from `routes.seed` on **every** boot, so a
         *     deleted route that is also in the seed returns — remove it from the seed
         *     as well — while the Redis store seeds once per namespace and keeps the
         *     deletion.
         */
        delete: operations["deleteRoute"];
        options?: never;
        head?: never;
        /**
         * Patch a route definition
         * @description Only `enabled`, `methods`, `ip_rules`, and `metadata` are patchable.
         *     `path` and `id` are **immutable** here — moving a route changes which
         *     requests it captures, which is a `PUT` (a full, reviewable definition),
         *     not a patch — and answer `400 invalid_route` with
         *     `message: "immutable; use PUT"`.
         */
        patch: operations["updateRoute"];
        trace?: never;
    };
    "/admin/ip-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The global IP rules */
        get: operations["getIpRules"];
        /**
         * Replace the global IP rules
         * @description Ordered, first match wins, and `default` decides the case no rule
         *     matched. Both `default` and `rules` are required — omitting either is a
         *     `400`, not a silent default. These are a **floor**: a global `deny`
         *     always wins, including over a route's own `allow`. CIDRs are parsed at
         *     write time, so a typo is a `400` here rather than a
         *     silently-never-matching rule on the hot path.
         */
        put: operations["putIpRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            instance: string;
            /** @description The roles this node runs, sorted. */
            roles: ("claim_check" | "dispatch" | "edge" | "storage")[];
        };
        /** @description A dead-lettered hook. The recorded reason is `inspect/1` of a term. */
        DlqEntry: {
            /** @description Envelope id (a UUIDv7). */
            id: string;
            source_id: string;
            tenant_id: string | null;
            /** @description WAL sequence number, `null` if the record never committed. */
            seq: number | null;
            /** @description When the edge received the hook, unix milliseconds. */
            received_at: number;
            /** @description When dispatch gave up, unix milliseconds. */
            dead_lettered_at: number;
            size: number;
            content_type: string | null;
            /** @description `inspect/1` of the give-up reason, e.g. `{:sink, Ankusa.Sink.Http, {:status, 503}}`. */
            reason: string;
        };
        DlqPage: {
            /** @description Number of matching entries, before `limit`. */
            total: number;
            entries: components["schemas"]["DlqEntry"][];
        };
        QuarantineEntry: {
            id: string;
            source_id: string;
            /** @description When the edge received the hook, unix milliseconds. */
            received_at: number;
            /** @description `inspect/1` of the verifier failure, e.g. `:no_match`. */
            reason: string;
        };
        QuarantinePage: {
            entries: components["schemas"]["QuarantineEntry"][];
        };
        ReplayFilter: {
            /** @description Exact source id. */
            source_id?: string;
            /** @description Exact envelope id. */
            id?: string;
            /** @description Inclusive lower bound on the dead-letter timestamp, unix milliseconds. */
            since?: number;
        };
        Replayed: {
            /** @description Number of entries re-delivered. */
            replayed: number;
        };
        /**
         * @description `GET /health` on the `routes.admin.port` listener: how many route
         *     definitions this node is enforcing.
         */
        RoutesHealth: {
            /** @constant */
            status: "ok";
            /**
             * @description The number of route definitions in the table, enabled or not.
             * @example 1
             */
            routes: number;
        };
        /** @description One rule. `cidr` is parsed at write time, so an unparseable one is a `400`. */
        IpRule: {
            /** @enum {string} */
            action: "allow" | "deny";
            /**
             * @description An IPv4 or IPv6 network. A bare address is a full-length prefix
             *     (`10.1.2.3` is `/32`). Families never cross: `0.0.0.0/0` matches only
             *     IPv4, `::/0` only IPv6, and an IPv4-mapped client (`::ffff:10.1.2.3`)
             *     is normalized to IPv4 before matching.
             * @example 203.0.113.0/24
             */
            cidr: string;
        };
        /**
         * @description The global IP rules: a floor every route inherits. A route's own
         *     `ip_rules` replace this list *for that route*, but a global `deny` has
         *     already won by then.
         */
        IpRules: {
            /**
             * @description Applied when no rule in `rules` matched.
             * @enum {string}
             */
            default: "allow" | "deny";
            /** @description Ordered; the first match wins. */
            rules: components["schemas"]["IpRule"][];
        };
        /**
         * @description A route definition: the capture gate. It decides whether a request is
         *     captured, not which source it belongs to.
         */
        Route: {
            /**
             * @description A lowercase slug, `^[a-z0-9](?:[a-z0-9_-]{0,62}[a-z0-9])?$`, supplied
             *     by the client or generated (a lowercase ULID). Immutable after
             *     creation.
             * @example stripe
             */
            id: string;
            /**
             * @description A pattern, not a regex: `/`-separated segments, each a literal, a
             *     `:param` (exactly one segment), or a trailing `*` wildcard (one or
             *     more segments — `/hooks/shopify/*` does not match `/hooks/shopify`).
             *     Requests are normalized before matching, and a percent-encoded slash
             *     (`%2F`) or a `.`/`..` segment is a rejection, not a boundary.
             * @example /webhooks/stripe
             */
            path: string;
            /**
             * @description The methods this route captures. Defaults to `[POST]`.
             * @example [
             *       "POST"
             *     ]
             */
            methods: string[];
            /**
             * @description A disabled route captures nothing — and is exempt from the duplicate
             *     check, so a staged definition may sit next to a live one.
             */
            enabled: boolean;
            /**
             * @description Empty (the default) means the global list applies. Non-empty
             *     **replaces** it for this route, and a client matching none of them is
             *     denied: the point of pinning a provider's ranges is that anything
             *     else is refused.
             */
            ip_rules: components["schemas"]["IpRule"][];
            /**
             * @description Free-form JSON for the operator — an owner, a sender name.
             * @example {
             *       "owner": "payments"
             *     }
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Set once, at creation. A `PUT` keeps it; a `PATCH` cannot touch it.
             * @example 2026-09-28T14:16:26Z
             */
            inserted_at: string;
            /**
             * Format: date-time
             * @example 2026-09-28T14:16:26Z
             */
            updated_at: string;
        };
        /**
         * @description A route definition as written. Unknown keys are a `400 invalid_route`
         *     (`"unknown field"`), as are `inserted_at`/`updated_at`: an update cannot
         *     forge its own history.
         */
        RouteInput: {
            /** @description Optional on create. On `PUT` the path's `id` wins. */
            id?: string;
            /** @example /webhooks/stripe */
            path: string;
            /**
             * @default [
             *       "POST"
             *     ]
             */
            methods: string[];
            /** @default true */
            enabled: boolean;
            /** @default [] */
            ip_rules: components["schemas"]["IpRule"][];
            /** @default {} */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Only these four fields are patchable. `path` and `id` answer
         *     `400 invalid_route` with `message: "immutable; use PUT"`.
         */
        RoutePatch: {
            enabled?: boolean;
            methods?: string[];
            ip_rules?: components["schemas"]["IpRule"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        RoutePage: {
            routes: components["schemas"]["Route"][];
            /**
             * @description The last id of this page when another page exists — pass it back as
             *     `cursor`. `null` on the last page.
             * @example null
             */
            next_cursor: string | null;
        };
        DryRunRequest: {
            /** @example POST */
            method: string;
            /**
             * @description The request path as the client would send it, normalization included.
             * @example /webhooks/stripe
             */
            path: string;
            /**
             * @description The client address. `X-Forwarded-For` resolution is the guard's job, not the dry run's.
             * @example 203.0.113.7
             */
            ip: string;
        };
        /** @description The rule that produced an IP decision, and the list it came from. */
        DryRunIpRule: {
            /** @enum {string} */
            action: "allow" | "deny";
            /** @example 203.0.113.0/24 */
            cidr: string;
            /**
             * @description `global` for `routes.ip_rules`, `route` for the matched route's own
             *     list.
             * @enum {string}
             */
            scope: "global" | "route";
        };
        DryRunResult: {
            /** @enum {string} */
            decision: "allow" | "deny";
            /**
             * @description `matched` is the only `allow`. `no_route` and `method` are both a
             *     `404` to the sender, so a probe cannot learn which paths exist;
             *     `ip_denied` is a `403` (or a `404` with
             *     `routes.ip_denied_status: 404`).
             * @enum {string}
             */
            reason: "matched" | "no_route" | "method" | "ip_denied";
            /**
             * @description The matched route, when one matched — including when its own rules then denied the address.
             * @example stripe
             */
            route_id: string | null;
            /**
             * @description The rule that decided the IP question — the global list's or the
             *     matched route's own — or `null` when no rule decided: a list's
             *     `default` applied because nothing matched, or the reason is not an
             *     IP decision (`no_route`, `method`). A route's own `allow` rule
             *     deciding a `matched` decision is reported here too.
             */
            ip_rule: components["schemas"]["DryRunIpRule"] | null;
        };
        /** @description The error shape every endpoint answers with, on every listener. */
        Error: {
            /** @enum {string} */
            error: "not_found" | "invalid_filter" | "role_not_enabled" | "invalid_route" | "duplicate_route" | "too_many_routes" | "invalid_query" | "invalid_ip_rules" | "invalid_request" | "invalid_body" | "store_unavailable";
            /**
             * @description The offending field: on `invalid_filter` the parameter or `body`; on
             *     the route errors the route field (`path`, `ip_rules`, …), the
             *     parameter (`enabled`, `limit`), or the dry-run field.
             */
            field?: string;
            /** @description Human-readable reason, on the `invalid_*` codes that carry one. */
            message?: string;
            /** @description Present on `role_not_enabled`; the role this node does not run. */
            role?: string;
            /** @description Present on `duplicate_route`; the route already holding that path and method. */
            conflicting_id?: string;
            /** @description Present on `too_many_routes`; the configured cap. */
            max_routes?: number;
        };
    };
    responses: {
        /** @description `400`. `invalid_filter`: a non-integer `since` or `limit`, a non-string `source_id` or `id`, or a replay body that is not a JSON object or is over 64 KiB. `field` names the offending parameter, or `body`. */
        InvalidFilter: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `409`. `role_not_enabled`: this node does not run the role the route needs. Ask another node. */
        RoleNotEnabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_route`: a route definition that would not mean what it says — a path that is not rooted or has an illegal segment, a non-boolean `enabled`, a bad CIDR, unknown fields, or `path`/`id` in a `PATCH`. `field` names it and `message` says why. Also `invalid_body` when the body never parsed. */
        InvalidRoute: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_query`: a `limit` that is not an integer, or an `enabled` that is neither `true` nor `false`. `field` names it. */
        InvalidQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_request`: the dry run's `method`, `path`, or `ip` is missing or unusable. `field` names it. Also `invalid_body` when the request body never parsed. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_ip_rules`: both `default` and `rules` are required, `default` is `allow` or `deny`, `rules` is a list, and every rule is an object with an `action` of `allow`/`deny` and a `cidr` that parses. A range inside `::ffff:0:0/96` parses but is refused, because client addresses are matched as IPv4 and such a range could never match; write the equivalent IPv4 CIDR. `field` is `default` or `rules`; a bad rule's `message` names its index (`rule 0: ...`). A body that is not a JSON object is `invalid_body`, not this. */
        InvalidIpRules: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `409`. `duplicate_route`: an enabled route already captures this path and one of these methods, or a `POST` names an id that is taken. `conflicting_id` is the route holding it. Also `too_many_routes`: the store is at `routes.max_routes`, and nothing is evicted to make room — delete a route instead. */
        DuplicateRoute: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `404`. `not_found`: no such route, or no such path on this listener. A method the path does not serve is also a `404`, deliberately — a probe cannot tell a missing path from a wrong method. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `503`. `store_unavailable`: nothing was written. Either the route store could not be reached (a Redis store with Redis down), or the write kept losing to concurrent writers and exhausted its retries — the table changed under the snapshot it had validated, every time. Both are transient: retry, and reads keep working from this node's in-memory snapshot either way. */
        StoreUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The listener is up. On `admin.port` the body is
             *     `{status, instance, roles}`; on `routes.admin.port` it is
             *     `{status, routes}`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"] | components["schemas"]["RoutesHealth"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition format, version 0.0.4. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example ankusa_ingest_requests_total{instance="default",outcome="committed",source_id="demo"} 1 */
                    "text/plain": string;
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description A JSON object mirroring the config's nesting. `{module, opts}`
             *     becomes `{"module": "...", "opts": {...}}`; keyword lists become
             *     objects; atoms become strings.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listDeadLetters: {
        parameters: {
            query?: {
                /** @description Exact source id to filter on. */
                source_id?: string;
                /** @description Inclusive lower bound on when the hook was dead-lettered, in unix milliseconds. */
                since?: number;
                /** @description Maximum entries returned. Values outside 0..1000 are clamped to that range. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching entries, newest first. `total` counts all matches, before `limit`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DlqPage"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            409: components["responses"]["RoleNotEnabled"];
        };
    };
    replayDeadLetters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A filter, not a payload. Omitted or empty (`{}`) replays everything.
         *     Unknown keys are ignored.
         */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReplayFilter"];
            };
        };
        responses: {
            /** @description The number of entries replayed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replayed"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            409: components["responses"]["RoleNotEnabled"];
        };
    };
    listQuarantined: {
        parameters: {
            query?: {
                /** @description Maximum entries returned. Values outside 0..1000 are clamped to that range. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent quarantined entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinePage"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            409: components["responses"]["RoleNotEnabled"];
        };
    };
    testRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "method": "POST",
                 *       "path": "/webhooks/stripe",
                 *       "ip": "203.0.113.7"
                 *     }
                 */
                "application/json": components["schemas"]["DryRunRequest"];
            };
        };
        responses: {
            /** @description The decision, and what produced it: `decision: deny` with the `reason` that denied it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            400: components["responses"]["InvalidRequest"];
        };
    };
    listRoutes: {
        parameters: {
            query?: {
                /**
                 * @description Filter by `enabled`. Anything other than `true`/`false` is `400 invalid_query`.
                 * @example true
                 */
                enabled?: "true" | "false";
                /**
                 * @description Maximum routes per page. Clamped to 1..200.
                 * @example 100
                 */
                limit?: number;
                /**
                 * @description The `next_cursor` of the previous page; returns ids greater than it.
                 * @example checkout
                 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of route definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePage"];
                };
            };
            400: components["responses"]["InvalidQuery"];
        };
    };
    createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "id": "stripe",
                 *       "path": "/webhooks/stripe",
                 *       "methods": [
                 *         "POST"
                 *       ],
                 *       "ip_rules": [
                 *         {
                 *           "action": "allow",
                 *           "cidr": "203.0.113.0/24"
                 *         }
                 *       ],
                 *       "metadata": {
                 *         "owner": "payments"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description The stored route, timestamps included. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["InvalidRoute"];
            409: components["responses"]["DuplicateRoute"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "/webhooks/stripe",
                 *       "methods": [
                 *         "POST"
                 *       ],
                 *       "enabled": false,
                 *       "ip_rules": [],
                 *       "metadata": {
                 *         "owner": "payments",
                 *         "staging": true
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description The stored route, with the `inserted_at` it already had. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["InvalidRoute"];
            409: components["responses"]["DuplicateRoute"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    updateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "enabled": true
                 *     }
                 */
                "application/json": components["schemas"]["RoutePatch"];
            };
        };
        responses: {
            /** @description The patched route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["InvalidRoute"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["DuplicateRoute"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getIpRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ordered global rules, and the `default` when none match. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRules"];
                };
            };
        };
    };
    putIpRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "default": "deny",
                 *       "rules": [
                 *         {
                 *           "action": "allow",
                 *           "cidr": "203.0.113.0/24"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["IpRules"];
            };
        };
        responses: {
            /** @description The stored rules, as parsed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRules"];
                };
            };
            400: components["responses"]["InvalidIpRules"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
}
