/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Both listeners answer this path, with a different body: the operator API
         *     reports the instance and the roles this node runs, the route-management
         *     API reports the size of the route table it is enforcing.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description The node's `Ankusa.Metrics` scrape: ingest, verification, store commit,
         *     load shedding, quarantine, dispatch, compaction, and claim-check
         *     series. Only the events this node emits appear — an edge node has no
         *     dispatch series, a storage node has no ingest series.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The effective, redacted configuration
         * @description The whole `Ankusa.Config` as the node resolved it: defaults, then the
         *     YAML file, then env overrides. Secrets are redacted by key name
         *     (`secret`, `password`, `secret_access_key`, `token`, `sasl`, `nkey_seed`)
         *     and by shape (a URI password becomes `user:[REDACTED]`), so this
         *     is safe to hand to anyone who can reach the port.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asyncapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AsyncAPI 3.0 document of this instance's messaging channels
         * @description Every Kafka topic, RabbitMQ routing key, NATS subject, and Redis channel
         *     this instance publishes delivered hooks to, built from the sources and
         *     sinks configured right now, plus the lifecycle events channel when
         *     `lifecycle.sinks` is set. Each message is an `Ankusa.Sink.Message` v1
         *     envelope (`SinkMessageV1` in `components.schemas`). Sinks without a
         *     channel (`log`, `http`) are left out. Carries no credentials.
         *
         *     The body is JSON, which AsyncAPI tooling reads as YAML 1.2.
         */
        get: operations["getAsyncApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This node's queue statistics
         * @description `Ankusa.Queue.stats/1` from this node's own store, `{}` when the store
         *     is unreachable. Node-local, like the DLQ and the quarantine list: ask
         *     every node. A node running `wal.type: none` has no queue to report.
         */
        get: operations["getWal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dead-lettered hooks
         * @description Newest first, metadata only — bodies are never returned. Results are
         *     this node's dead delivery rows; with several dispatch nodes, ask each one.
         */
        get: operations["listDeadLetters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List replay jobs
         * @description Every replay job, newest first.
         */
        get: operations["listReplays"];
        put?: never;
        /**
         * Create a replay job
         * @description Creates a durable, paced replay job. `kind: dlq` re-sends dead delivery
         *     rows; `kind: archive` re-sends archived hooks over a `received_at`
         *     window; `kind: quarantine` re-verifies hooks held in this node's
         *     quarantine pen against each source's current verifier (the timestamp
         *     window judged at the hook's receive time) and commits the ones that now
         *     pass as new hooks, with the hook's original `id`. Held hooks that still
         *     fail stay in the pen. Rows are dripped in at `rate` items per second,
         *     only while the dispatch pipeline's oldest-due lag is at most
         *     `max_lag_ms` and its in-flight window is not full, so a replay only
         *     uses capacity live traffic leaves free. A `dlq` or `quarantine` job
         *     touches only entries dead-lettered or quarantined at or before its own
         *     creation time. Every replayed delivery keeps the hook's original `id`
         *     and `dedupe_key` and carries the job id as `replay_id`.
         *     Posting the same spec again while a `running` or `paused` job with the
         *     same kind and filter exists returns that job (200), so a proxy retry
         *     is idempotent.
         */
        post: operations["createReplay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/replays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One replay job */
        get: operations["getReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Pause, resume, cancel, or re-rate a replay job
         * @description `state` is `running`, `paused` or `cancelled`; resuming clears `error`
         *     and resets the auto-pause window. `rate` and `max_lag_ms` take effect
         *     at once. A `done`, `cancelled` or `failed` job refuses patches with
         *     `replay_finished`.
         */
        patch: operations["updateReplay"];
        trace?: never;
    };
    "/v1/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent quarantined hooks
         * @description The newest quarantined entries from this node's store, newest first.
         *     Metadata only — bodies are never returned; the whole request stays in
         *     the store until a `quarantine` replay job releases it or a purge
         *     deletes it.
         */
        get: operations["listQuarantined"];
        put?: never;
        post?: never;
        /**
         * Delete quarantined hooks
         * @description Deletes up to `limit` entries matching every given filter, oldest
         *     first, in one synced batch, and frees their bytes against
         *     `quarantine.max_bytes`. No filter deletes the oldest `limit` entries.
         *     Deleted hooks are gone for good — to keep the ones that now verify, run
         *     a `quarantine` replay job first.
         */
        delete: operations["purgeQuarantined"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rate-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every limit this node enforces
         * @description The configured default and the configured tenants, unioned with this
         *     node's runtime overrides (an override wins). Sorted by tenant id.
         *     `default` is `null` when the config sets none, which with no tenant
         *     entry means unlimited.
         */
        get: operations["listRateLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tenant}/rate-limit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tenant id, as it appears in the catch URL. */
                tenant: string;
            };
            cookie?: never;
        };
        /**
         * The limit that applies to one tenant
         * @description The override when this node has one, else `rate_limits.tenants`, else
         *     `rate_limits.default` — with `source` saying which. `source: none` means
         *     unlimited; `rate` and `burst` are `null` then.
         */
        get: operations["getTenantRateLimit"];
        /**
         * Set a tenant's override
         * @description Stored in this node's memory and persisted to its store, so it
         *     survives a restart of this node. Takes effect at once: the tenant's
         *     bucket is reset, so a raised limit is not held back by the old limit's
         *     accumulated debt. A `{rate, burst}` pair is required whole — neither key
         *     is inferred.
         */
        put: operations["putTenantRateLimit"];
        post?: never;
        /**
         * Remove a tenant's override
         * @description The config's limit applies again (`source: config` or `default`), and
         *     the bucket is reset. Immediate, like the source store's own deletes —
         *     and, like them, this node's alone.
         */
        delete: operations["deleteTenantRateLimit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry run — what would happen to this request?
         * @description Runs the same decision the guard runs, and reports it: the global IP
         *     rules first, then route matching, then the matched route's own rules.
         *     Nothing is captured, no counter moves, and the decision cache is
         *     neither read nor written — a dry run cannot make a path look hot, and
         *     it never answers from an entry another request wrote. This is the
         *     endpoint that turns "why was my webhook rejected" into one call, and it
         *     is worth using before changing any route.
         *
         *     `ip_rule` is the rule that *decided* an IP question, with the list it
         *     came from (`scope`); it is `null` whenever no rule decided — a list's
         *     `default` (nothing matched), or a reason that is not an IP decision at
         *     all.
         */
        post: operations["testRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List route definitions
         * @description Ordered by id, which is a total order over the slug alphabet and so also
         *     a pagination cursor. `next_cursor` is `null` on the last page.
         */
        get: operations["listRoutes"];
        put?: never;
        /**
         * Create a route definition
         * @description `id` is optional: without one, a lowercase ULID is generated. A taken id
         *     is a `409 duplicate_route`, and an **enabled** route may not capture the
         *     same normalized path and any of the same methods as another enabled
         *     route (two disabled routes are free to collide — they capture nothing).
         *     Past `routes.max_routes` the answer is `409 too_many_routes`; nothing is
         *     ever evicted, because an evicted route would start rejecting real
         *     webhooks.
         *
         *     The id `test` is **not** reserved: only the `POST /admin/routes/test`
         *     *dry run* shadows this path, and it shadows it for `POST` alone. `POST
         *     /admin/routes` with `{"id": "test"}` creates that route like any other
         *     id, and `GET`/`PUT`/`PATCH`/`DELETE /admin/routes/test` then address it
         *     normally.
         */
        post: operations["createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        /** Fetch one route definition */
        get: operations["getRoute"];
        /**
         * Replace a route definition
         * @description A full definition, `PUT`-idempotent: the `id` comes from the path (a body
         *     `id` is ignored), `inserted_at` is preserved, and `updated_at` moves. A
         *     `PUT` for an id that does not exist yet *creates* it, so the cap applies
         *     to that case too.
         */
        put: operations["replaceRoute"];
        post?: never;
        /**
         * Delete a route definition
         * @description Immediate: the guard stops capturing the route on the next request, with
         *     no cache TTL to wait out — the decision cache is keyed by the published
         *     snapshot's epoch, so a mutation makes every cached decision unreachable.
         *     Whether a restart brings the route back is the store's question: the
         *     default ETS store re-seeds from `routes.seed` on **every** boot, so a
         *     deleted route that is also in the seed returns — remove it from the seed
         *     as well — while the Redis store seeds once per namespace and keeps the
         *     deletion.
         */
        delete: operations["deleteRoute"];
        options?: never;
        head?: never;
        /**
         * Patch a route definition
         * @description Only `enabled`, `methods`, `ip_rules`, and `metadata` are patchable.
         *     `path` and `id` are **immutable** here — moving a route changes which
         *     requests it captures, which is a `PUT` (a full, reviewable definition),
         *     not a patch — and answer `400 invalid_route` with
         *     `message: "immutable; use PUT"`.
         */
        patch: operations["updateRoute"];
        trace?: never;
    };
    "/admin/ip-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The global IP rules */
        get: operations["getIpRules"];
        /**
         * Replace the global IP rules
         * @description Ordered, first match wins, and `default` decides the case no rule
         *     matched. Both `default` and `rules` are required — omitting either is a
         *     `400`, not a silent default. These are a **floor**: a global `deny`
         *     always wins, including over a route's own `allow`. CIDRs are parsed at
         *     write time, so a typo is a `400` here rather than a
         *     silently-never-matching rule on the hot path.
         */
        put: operations["putIpRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            instance: string;
            /** @description The roles this node runs, sorted. */
            roles: ("claim_check" | "dispatch" | "edge" | "storage")[];
        };
        Wal: {
            instance: string;
            /**
             * @description This node's store: `next_seq` (exact), `hooks` and `deliveries`
             *     (RocksDB key estimates), `disk_bytes`; `{}` when the store is
             *     unreachable.
             */
            wal: Record<string, never>;
        };
        /** @description A dead-lettered hook. The recorded reason is `inspect/1` of a term. */
        DlqEntry: {
            /** @description Envelope id (a UUIDv7). */
            id: string;
            source_id: string;
            tenant_id: string | null;
            /** @description Queue sequence number of the committed hook, `null` if it never committed. */
            seq: number | null;
            /** @description When the edge received the hook, unix milliseconds. */
            received_at: number;
            /** @description When dispatch gave up, unix milliseconds. */
            dead_lettered_at: number;
            size: number;
            content_type: string | null;
            /** @description `inspect/1` of the give-up reason, e.g. `{:sink, Ankusa.Sink.Http, {:status, 503}}`. */
            reason: string;
        };
        DlqPage: {
            /** @description Number of matching entries, before `limit`. */
            total: number;
            entries: components["schemas"]["DlqEntry"][];
        };
        QuarantineEntry: {
            id: string;
            source_id: string;
            /** @description The hook's tenant (`default` unless the source or a tenant route set one); `null` only for entries held before the pen recorded it. */
            tenant_id?: string | null;
            /** @description When the edge received the hook, unix milliseconds. */
            received_at: number;
            /** @description `inspect/1` of the verifier failure, e.g. `:no_match`. */
            reason: string;
            /** @description Bytes the entry holds against `quarantine.max_bytes`; `null` for entries held before the pen recorded it. */
            size?: number | null;
        };
        QuarantinePage: {
            entries: components["schemas"]["QuarantineEntry"][];
        };
        QuarantinePurge: {
            /** @description Entries deleted. */
            deleted: number;
            /** @description The bytes they held against `quarantine.max_bytes`. */
            bytes: number;
        };
        ReplaySpec: {
            /**
             * @description `dlq` re-sends dead rows; `archive` re-sends archived hooks over a
             *     time window; `quarantine` re-verifies hooks held in the quarantine
             *     pen and commits the ones that now pass.
             * @enum {string}
             */
            kind: "dlq" | "archive" | "quarantine";
            /** @description Exact source id to filter on. */
            source_id?: string;
            /** @description Exact envelope id to filter on (`dlq` and `quarantine` only). */
            id?: string;
            /**
             * @description Inclusive lower bound, unix milliseconds: on the dead-letter
             *     timestamp (`dlq`) or on `received_at` (`quarantine`).
             */
            since?: number;
            /**
             * @description Inclusive upper bound, unix milliseconds, on the same timestamp as
             *     `since` (`dlq` and `quarantine` only). Must not be less than `since`.
             */
            until?: number;
            /** @description Inclusive lower bound on `received_at`, unix milliseconds (`archive` only). */
            from?: number;
            /**
             * @description Inclusive upper bound on `received_at`, unix milliseconds
             *     (`archive` only). Must be greater than `from`, and old enough that
             *     the compactor has archived the whole window (`storage.roll_ms +
             *     storage.interval_ms` in the past).
             */
            to?: number;
            /** @description Indexes into the source's current sinks; omitted means every current sink (`archive` only). */
            sinks?: number[];
            /**
             * @description Items per second — delivery rows for `dlq`, hooks for `archive` and `quarantine`.
             * @default 1000
             */
            rate: number;
            /**
             * @description The oldest-due lag at which the job throttles, in milliseconds.
             * @default 2000
             */
            max_lag_ms: number;
        };
        ReplayPatch: {
            /** @enum {string} */
            state?: "running" | "paused" | "cancelled";
            rate?: number;
            max_lag_ms?: number;
        };
        /**
         * @description A replay job. Counters are best-effort: `moved`/`scanned`/`skipped` are
         *     committed with the job's cursor, `delivered`/`dead` come from the
         *     pipeline's outcome reports and are approximate across a crash.
         */
        Replay: {
            /** @description UUIDv7 job id; also the `replay_id` on every replayed delivery. */
            id: string;
            /** @enum {string} */
            kind: "dlq" | "archive" | "quarantine";
            /** @enum {string} */
            state: "running" | "paused" | "done" | "cancelled" | "failed";
            /** @description Exactly the filter keys given at creation. */
            filter: Record<string, never>;
            /** @description Items per second. */
            rate: number;
            /** @description Throttle threshold, milliseconds. */
            max_lag_ms: number;
            /** @description Unix milliseconds. */
            created_at: number;
            /** @description Unix milliseconds. */
            updated_at: number;
            /** @description Unix milliseconds, `null` until the job finishes. */
            finished_at: number | null;
            /** @description Rows revived (`dlq`), hooks re-enqueued (`archive`), or held hooks committed after passing verification again (`quarantine`). */
            moved: number;
            /** @description Keys or records examined. */
            scanned: number;
            /**
             * @description Archive records with no source, no bound sink, or an undecodable
             *     frame (`archive`); held hooks that still fail verification, whose
             *     source is gone, or that were a duplicate of a hook already
             *     accepted (`quarantine` — the duplicates leave the pen, the rest
             *     stay in it).
             */
            skipped: number;
            /** @description Deliveries this job's rows got through, per pipeline outcome reports. */
            delivered: number;
            /** @description Deliveries this job's rows dead-lettered again, per pipeline outcome reports. */
            dead: number;
            /** @description `null`, or why the job paused itself or failed. */
            error: string | null;
        };
        ReplayList: {
            replays: components["schemas"]["Replay"][];
        };
        /**
         * @description A rate limit. `rate` is hooks per second and may be fractional (`0.5`
         *     is one every two seconds); `burst` is the most hooks admitted back to
         *     back.
         */
        RateLimit: {
            /** @example 50 */
            rate: number;
            /** @example 100 */
            burst: number;
        };
        /** @description One tenant's limit, and whether it came from config or an override. */
        TenantRateLimit: {
            tenant: string;
            /** @description `null` when `source` is `none`. */
            rate: number | null;
            /** @description `null` when `source` is `none`. */
            burst: number | null;
            /**
             * @description `override`: this node's runtime override. `config`:
             *     `rate_limits.tenants`. `default`: `rate_limits.default`. `none`: no
             *     limit applies, so the tenant is unlimited.
             * @enum {string}
             */
            source: "override" | "config" | "default" | "none";
        };
        RateLimits: {
            /**
             * @description The configured `rate_limits.default`, or `null` when the config sets
             *     none. It is never an override: overrides are per tenant.
             */
            default: components["schemas"]["RateLimit"] | null;
            /** @description Sorted by tenant id. */
            tenants: components["schemas"]["TenantRateLimit"][];
        };
        /**
         * @description `GET /health` on the `routes.admin.port` listener: how many route
         *     definitions this node is enforcing.
         */
        RoutesHealth: {
            /** @constant */
            status: "ok";
            /**
             * @description The number of route definitions in the table, enabled or not.
             * @example 1
             */
            routes: number;
        };
        /** @description One rule. `cidr` is parsed at write time, so an unparseable one is a `400`. */
        IpRule: {
            /** @enum {string} */
            action: "allow" | "deny";
            /**
             * @description An IPv4 or IPv6 network. A bare address is a full-length prefix
             *     (`10.1.2.3` is `/32`). Families never cross: `0.0.0.0/0` matches only
             *     IPv4, `::/0` only IPv6, and an IPv4-mapped client (`::ffff:10.1.2.3`)
             *     is normalized to IPv4 before matching.
             * @example 203.0.113.0/24
             */
            cidr: string;
        };
        /**
         * @description The global IP rules: a floor every route inherits. A route's own
         *     `ip_rules` replace this list *for that route*, but a global `deny` has
         *     already won by then.
         */
        IpRules: {
            /**
             * @description Applied when no rule in `rules` matched.
             * @enum {string}
             */
            default: "allow" | "deny";
            /** @description Ordered; the first match wins. */
            rules: components["schemas"]["IpRule"][];
        };
        /**
         * @description A route definition: the capture gate. It decides whether a request is
         *     captured, not which source it belongs to.
         */
        Route: {
            /**
             * @description A lowercase slug, `^[a-z0-9](?:[a-z0-9_-]{0,62}[a-z0-9])?$`, supplied
             *     by the client or generated (a lowercase ULID). Immutable after
             *     creation.
             * @example stripe
             */
            id: string;
            /**
             * @description A pattern, not a regex: `/`-separated segments, each a literal, a
             *     `:param` (exactly one segment), or a trailing `*` wildcard (one or
             *     more segments — `/hooks/shopify/*` does not match `/hooks/shopify`).
             *     Requests are normalized before matching, and a percent-encoded slash
             *     (`%2F`) or a `.`/`..` segment is a rejection, not a boundary.
             * @example /webhooks/stripe
             */
            path: string;
            /**
             * @description The methods this route captures. Defaults to `[POST]`.
             * @example [
             *       "POST"
             *     ]
             */
            methods: string[];
            /**
             * @description A disabled route captures nothing — and is exempt from the duplicate
             *     check, so a staged definition may sit next to a live one.
             */
            enabled: boolean;
            /**
             * @description Empty (the default) means the global list applies. Non-empty
             *     **replaces** it for this route, and a client matching none of them is
             *     denied: the point of pinning a provider's ranges is that anything
             *     else is refused.
             */
            ip_rules: components["schemas"]["IpRule"][];
            /**
             * @description Free-form JSON for the operator — an owner, a sender name.
             * @example {
             *       "owner": "payments"
             *     }
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Set once, at creation. A `PUT` keeps it; a `PATCH` cannot touch it.
             * @example 2026-09-28T14:16:26Z
             */
            inserted_at: string;
            /**
             * Format: date-time
             * @example 2026-09-28T14:16:26Z
             */
            updated_at: string;
        };
        /**
         * @description A route definition as written. Unknown keys are a `400 invalid_route`
         *     (`"unknown field"`), as are `inserted_at`/`updated_at`: an update cannot
         *     forge its own history.
         */
        RouteInput: {
            /** @description Optional on create. On `PUT` the path's `id` wins. */
            id?: string;
            /** @example /webhooks/stripe */
            path: string;
            /**
             * @default [
             *       "POST"
             *     ]
             */
            methods: string[];
            /** @default true */
            enabled: boolean;
            /** @default [] */
            ip_rules: components["schemas"]["IpRule"][];
            /** @default {} */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Only these four fields are patchable. `path` and `id` answer
         *     `400 invalid_route` with `message: "immutable; use PUT"`.
         */
        RoutePatch: {
            enabled?: boolean;
            methods?: string[];
            ip_rules?: components["schemas"]["IpRule"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        RoutePage: {
            routes: components["schemas"]["Route"][];
            /**
             * @description The last id of this page when another page exists — pass it back as
             *     `cursor`. `null` on the last page.
             * @example null
             */
            next_cursor: string | null;
        };
        DryRunRequest: {
            /** @example POST */
            method: string;
            /**
             * @description The request path as the client would send it, normalization included.
             * @example /webhooks/stripe
             */
            path: string;
            /**
             * @description The client address. `X-Forwarded-For` resolution is the guard's job, not the dry run's.
             * @example 203.0.113.7
             */
            ip: string;
        };
        /** @description The rule that produced an IP decision, and the list it came from. */
        DryRunIpRule: {
            /** @enum {string} */
            action: "allow" | "deny";
            /** @example 203.0.113.0/24 */
            cidr: string;
            /**
             * @description `global` for `routes.ip_rules`, `route` for the matched route's own
             *     list.
             * @enum {string}
             */
            scope: "global" | "route";
        };
        DryRunResult: {
            /** @enum {string} */
            decision: "allow" | "deny";
            /**
             * @description `matched` is the only `allow`. `no_route` and `method` are both a
             *     `404` to the sender, so a probe cannot learn which paths exist;
             *     `ip_denied` is a `403` (or a `404` with
             *     `routes.ip_denied_status: 404`).
             * @enum {string}
             */
            reason: "matched" | "no_route" | "method" | "ip_denied";
            /**
             * @description The matched route, when one matched — including when its own rules then denied the address.
             * @example stripe
             */
            route_id: string | null;
            /**
             * @description The rule that decided the IP question — the global list's or the
             *     matched route's own — or `null` when no rule decided: a list's
             *     `default` applied because nothing matched, or the reason is not an
             *     IP decision (`no_route`, `method`). A route's own `allow` rule
             *     deciding a `matched` decision is reported here too.
             */
            ip_rule: components["schemas"]["DryRunIpRule"] | null;
        };
        /** @description The error shape every endpoint answers with, on every listener. */
        Error: {
            /** @enum {string} */
            error: "not_found" | "invalid_filter" | "role_not_enabled" | "invalid_route" | "duplicate_route" | "too_many_routes" | "invalid_query" | "invalid_ip_rules" | "invalid_request" | "invalid_body" | "invalid_tenant" | "invalid_rate_limit" | "rate_limit_not_found" | "store_unavailable" | "wal_disabled";
            /**
             * @description The offending field: on `invalid_filter` the parameter or `body`; on
             *     the route errors the route field (`path`, `ip_rules`, …), the
             *     parameter (`enabled`, `limit`), or the dry-run field.
             */
            field?: string;
            /** @description Human-readable reason, on the `invalid_*` codes that carry one. */
            message?: string;
            /** @description Present on `role_not_enabled`; the role this node does not run. */
            role?: string;
            /** @description Present on `duplicate_route`; the route already holding that path and method. */
            conflicting_id?: string;
            /** @description Present on `too_many_routes`; the configured cap. */
            max_routes?: number;
        };
    };
    responses: {
        /** @description `400`. `invalid_filter`: a non-integer `since`, `until` or `limit`, a negative `since`/`until` or an `until` before `since` on a quarantine purge, a non-string `source_id` or `id`, a replay spec with an unknown key or a bad field (`kind`, `since`/`until`, `from`/`to`, `sinks`, `rate`, `max_lag_ms`, `state`), or a replay body that is not a JSON object or is over 64 KiB. `field` names the offending parameter or key. */
        InvalidFilter: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_tenant`: the tenant is not a valid identity — it must match `[A-Za-z0-9_-]{1,64}`, because it is a URL path segment and a storage partition. */
        InvalidTenant: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_rate_limit`: the body is not a JSON object, or not a limit — `rate` and `burst` are both required, `rate` is a number greater than 0, `burst` an integer of at least 1, and unknown fields are refused. `message` says which. */
        InvalidRateLimit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `409`. `role_not_enabled`: this node does not run the role the route needs. Ask another node. */
        RoleNotEnabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `404`. `replay_not_found`: this node holds no replay job with that id. */
        ReplayNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "replay_not_found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `409`. `wal_disabled`: this node runs `wal.type: none` and has no log to report. */
        WalDisabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "wal_disabled"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_route`: a route definition that would not mean what it says — a path that is not rooted or has an illegal segment, a non-boolean `enabled`, a bad CIDR, unknown fields, or `path`/`id` in a `PATCH`. `field` names it and `message` says why. Also `invalid_body` when the body never parsed. */
        InvalidRoute: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_query`: a `limit` that is not an integer, or an `enabled` that is neither `true` nor `false`. `field` names it. */
        InvalidQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_request`: the dry run's `method`, `path`, or `ip` is missing or unusable. `field` names it. Also `invalid_body` when the request body never parsed. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `400`. `invalid_ip_rules`: both `default` and `rules` are required, `default` is `allow` or `deny`, `rules` is a list, and every rule is an object with an `action` of `allow`/`deny` and a `cidr` that parses. A range inside `::ffff:0:0/96` parses but is refused, because client addresses are matched as IPv4 and such a range could never match; write the equivalent IPv4 CIDR. `field` is `default` or `rules`; a bad rule's `message` names its index (`rule 0: ...`). A body that is not a JSON object is `invalid_body`, not this. */
        InvalidIpRules: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `409`. `duplicate_route`: an enabled route already captures this path and one of these methods, or a `POST` names an id that is taken. `conflicting_id` is the route holding it. Also `too_many_routes`: the store is at `routes.max_routes`, and nothing is evicted to make room — delete a route instead. */
        DuplicateRoute: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `404`. `not_found`: no such route, or no such path on this listener. A method the path does not serve is also a `404`, deliberately — a probe cannot tell a missing path from a wrong method. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `404`. `rate_limit_not_found`: this node holds no runtime override for that tenant. The config may still give it a limit — `GET` reports that as `source: config` or `default`. */
        RateLimitNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `503`. `store_unavailable`: nothing was written. Either the route store could not be reached (a Redis store with Redis down), or the write kept losing to concurrent writers and exhausted its retries — the table changed under the snapshot it had validated, every time. Both are transient: retry, and reads keep working from this node's in-memory snapshot either way. */
        StoreUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `503`. `store_unavailable`: this node's store could not be read or written, so nothing changed. Transient: retry. */
        NodeStoreUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The listener is up. On `admin.port` the body is
             *     `{status, instance, roles}`; on `routes.admin.port` it is
             *     `{status, routes}`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"] | components["schemas"]["RoutesHealth"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition format, version 0.0.4. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example ankusa_ingest_requests_total{instance="default",outcome="committed",source_id="demo"} 1 */
                    "text/plain": string;
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description A JSON object mirroring the config's nesting. `{module, opts}`
             *     becomes `{"module": "...", "opts": {...}}`; keyword lists become
             *     objects; atoms become strings.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAsyncApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The AsyncAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/asyncapi+json": {
                        /** @constant */
                        asyncapi: "3.0.0";
                        info: Record<string, never>;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getWal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This node's queue statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wal"];
                };
            };
            409: components["responses"]["WalDisabled"];
        };
    };
    listDeadLetters: {
        parameters: {
            query?: {
                /** @description Exact source id to filter on. */
                source_id?: string;
                /** @description Inclusive lower bound on when the hook was dead-lettered, in unix milliseconds. */
                since?: number;
                /** @description Maximum entries returned. Values outside 0..1000 are clamped to that range. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching entries, newest first. `total` counts all matches, before `limit`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DlqPage"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    listReplays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All jobs, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayList"];
                };
            };
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    createReplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `kind` is required. Unknown keys are refused with `invalid_filter`.
         *     `since`/`until` are inclusive bounds (unix ms) on the dead-letter time
         *     for `dlq` and on `received_at` for `quarantine`; `from`/`to` are
         *     inclusive `received_at` bounds (unix ms) for `archive`, and `to` must
         *     be old enough that the compactor has archived the whole window.
         *     `sinks` indexes into the source's current sinks; omitted means every
         *     current sink.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaySpec"];
            };
        };
        responses: {
            /** @description An existing running or paused job with the same kind and filter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            /** @description The new job, running. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            /**
             * @description `role_not_enabled` (an `archive` or `quarantine` job on a node
             *     without a queue writer — both roles, `edge` and `dispatch`, must
             *     run) or `too_many_replays` (16 jobs already running or paused).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    getReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            404: components["responses"]["ReplayNotFound"];
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    updateReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayPatch"];
            };
        };
        responses: {
            /** @description The updated job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            404: components["responses"]["ReplayNotFound"];
            /** @description `role_not_enabled`, or `replay_finished` for a finished job. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    listQuarantined: {
        parameters: {
            query?: {
                /** @description Maximum entries returned. Values outside 0..1000 are clamped to that range. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent quarantined entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinePage"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    purgeQuarantined: {
        parameters: {
            query?: {
                /** @description Exact source id. */
                source_id?: string;
                /** @description Exact envelope id. */
                id?: string;
                /** @description Inclusive lower bound on `received_at`, unix milliseconds. */
                since?: number;
                /** @description Inclusive upper bound on `received_at`, unix milliseconds. Must not be less than `since`. */
                until?: number;
                /** @description Maximum entries deleted. Values outside 1..10000 are clamped to that range. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinePurge"];
                };
            };
            400: components["responses"]["InvalidFilter"];
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    listRateLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The default, if any, and every tenant with a limit — configured or overridden. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimits"];
                };
            };
            409: components["responses"]["RoleNotEnabled"];
        };
    };
    getTenantRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tenant id, as it appears in the catch URL. */
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The effective limit and where it came from. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantRateLimit"];
                };
            };
            400: components["responses"]["InvalidTenant"];
            409: components["responses"]["RoleNotEnabled"];
        };
    };
    putTenantRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tenant id, as it appears in the catch URL. */
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateLimit"];
            };
        };
        responses: {
            /** @description The stored override. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantRateLimit"];
                };
            };
            400: components["responses"]["InvalidRateLimit"];
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    deleteTenantRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tenant id, as it appears in the catch URL. */
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidTenant"];
            404: components["responses"]["RateLimitNotFound"];
            409: components["responses"]["RoleNotEnabled"];
            503: components["responses"]["NodeStoreUnavailable"];
        };
    };
    testRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "method": "POST",
                 *       "path": "/webhooks/stripe",
                 *       "ip": "203.0.113.7"
                 *     }
                 */
                "application/json": components["schemas"]["DryRunRequest"];
            };
        };
        responses: {
            /** @description The decision, and what produced it: `decision: deny` with the `reason` that denied it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            400: components["responses"]["InvalidRequest"];
        };
    };
    listRoutes: {
        parameters: {
            query?: {
                /**
                 * @description Filter by `enabled`. Anything other than `true`/`false` is `400 invalid_query`.
                 * @example true
                 */
                enabled?: "true" | "false";
                /**
                 * @description Maximum routes per page. Clamped to 1..200.
                 * @example 100
                 */
                limit?: number;
                /**
                 * @description The `next_cursor` of the previous page; returns ids greater than it.
                 * @example checkout
                 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of route definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePage"];
                };
            };
            400: components["responses"]["InvalidQuery"];
        };
    };
    createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "id": "stripe",
                 *       "path": "/webhooks/stripe",
                 *       "methods": [
                 *         "POST"
                 *       ],
                 *       "ip_rules": [
                 *         {
                 *           "action": "allow",
                 *           "cidr": "203.0.113.0/24"
                 *         }
                 *       ],
                 *       "metadata": {
                 *         "owner": "payments"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description The stored route, timestamps included. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["InvalidRoute"];
            409: components["responses"]["DuplicateRoute"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "/webhooks/stripe",
                 *       "methods": [
                 *         "POST"
                 *       ],
                 *       "enabled": false,
                 *       "ip_rules": [],
                 *       "metadata": {
                 *         "owner": "payments",
                 *         "staging": true
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description The stored route, with the `inserted_at` it already had. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["InvalidRoute"];
            409: components["responses"]["DuplicateRoute"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    updateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The route's id (a lowercase slug).
                 * @example stripe
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "enabled": true
                 *     }
                 */
                "application/json": components["schemas"]["RoutePatch"];
            };
        };
        responses: {
            /** @description The patched route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["InvalidRoute"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["DuplicateRoute"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getIpRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ordered global rules, and the `default` when none match. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRules"];
                };
            };
        };
    };
    putIpRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "default": "deny",
                 *       "rules": [
                 *         {
                 *           "action": "allow",
                 *           "cidr": "203.0.113.0/24"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["IpRules"];
            };
        };
        responses: {
            /** @description The stored rules, as parsed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRules"];
                };
            };
            400: components["responses"]["InvalidIpRules"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
}
