/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/claims/{tenant_id}/{object_id}/{offset}/{length}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The claim's tenant. Never needs encoding. */
                tenant_id: components["parameters"]["TenantId"];
                /** @description The pack object's id, an RFC 9562 UUIDv7, lowercase and hyphenated. */
                object_id: components["parameters"]["ObjectId"];
                /** @description Byte offset of the claim inside the object. Decimal, no leading zeros. */
                offset: components["parameters"]["Offset"];
                /** @description Length of the claim in bytes. Decimal, no leading zeros, at least 1. */
                length: components["parameters"]["Length"];
            };
            cookie?: never;
        };
        /**
         * Read a claim's bytes
         * @description Returns exactly `length` bytes starting at `offset` in the object.
         *     Objects are written once and never rewritten, so a response is
         *     cacheable forever. The server does not verify integrity: the reader
         *     MUST check the bytes against the sha256 in its ref.
         */
        get: operations["readClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example acme */
        TenantId: string;
        /** @example 0199a1c2-7b3e-7d4a-9c1f-2e5b8a6d4f10 */
        UUIDv7: string;
        /**
         * @description A claim-check ref, as carried in a queue message's `claim` field.
         *     Segments: tenant, object id, offset, length, and the claim's sha256
         *     (lowercase hex).
         * @example urn:ankusa:claim:v1:acme:0199a1c2-7b3e-7d4a-9c1f-2e5b8a6d4f10:66:3145728:sha256-3bea8a9a07c1e8dcaa4c1b816815c35a29b4fb585ba6ecc70ea44840a794cfb3
         */
        Ref: string;
        Error: {
            /** @enum {string} */
            error: "invalid_tenant" | "invalid_id" | "invalid_range" | "not_found" | "store_unavailable";
        };
        Health: {
            /** @constant */
            status: "ok";
        };
    };
    responses: {
        /** @description `invalid_tenant`, `invalid_id`, or `invalid_range` (a malformed offset or length). Permanent. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `not_found`: no such object, or no such route. Permanent. Dead-letter, do not requeue. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `invalid_range`: the range runs past the end of the object. Permanent. */
        RangeNotSatisfiable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `store_unavailable`. Transient. Retry. */
        StoreUnavailable: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The claim's tenant. Never needs encoding. */
        TenantId: components["schemas"]["TenantId"];
        /** @description The pack object's id, an RFC 9562 UUIDv7, lowercase and hyphenated. */
        ObjectId: components["schemas"]["UUIDv7"];
        /** @description Byte offset of the claim inside the object. Decimal, no leading zeros. */
        Offset: string;
        /** @description Length of the claim in bytes. Decimal, no leading zeros, at least 1. */
        Length: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The claim's tenant. Never needs encoding. */
                tenant_id: components["parameters"]["TenantId"];
                /** @description The pack object's id, an RFC 9562 UUIDv7, lowercase and hyphenated. */
                object_id: components["parameters"]["ObjectId"];
                /** @description Byte offset of the claim inside the object. Decimal, no leading zeros. */
                offset: components["parameters"]["Offset"];
                /** @description Length of the claim in bytes. Decimal, no leading zeros, at least 1. */
                length: components["parameters"]["Length"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The claim's bytes. */
            200: {
                headers: {
                    /** @description Always `public, max-age=31536000, immutable`. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            416: components["responses"]["RangeNotSatisfiable"];
            503: components["responses"]["StoreUnavailable"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listener is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
